#include <Servo.h>
#include <DHT.h>
#include <DHT_U.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/13b15d97-2437-49dd-b8dd-9c3983c67665 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight fan;
  CloudLight light1;
  CloudLight light2;
  CloudTemperatureSensor room_temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define RELAY1 14
#define RELAY2 12
#define RELAY3 13
#define TEMP 1
#define TEMP_THRESHOLD 30.0
DHT dht(TEMP,DHT11);
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(RELAY1,OUTPUT);
  pinMode(RELAY2,OUTPUT);
  pinMode(RELAY3,OUTPUT);
  digitalWrite(RELAY1,HIGH);
  digitalWrite(RELAY2,HIGH);
  digitalWrite(RELAY3,HIGH);
  dht.begin();
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  room_temperature = dht.readTemperature();
  if (room_temperature > TEMP_THRESHOLD) 
      digitalWrite(RELAY3, LOW);  // Turn the fan ON
  else 
      digitalWrite(RELAY3, HIGH); // Turn the fan OFF
  
}

/*
  Since Light1 is READ_WRITE variable, onLight1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight1Change()  {
  if(light1)
    digitalWrite(RELAY1,LOW);
  else
    digitalWrite(RELAY1,HIGH);
}

/*
  Since Light2 is READ_WRITE variable, onLight2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight2Change()  {
  if(light2)
    digitalWrite(RELAY2,LOW);
  else
    digitalWrite(RELAY2,HIGH);
}


/*
  Since Fan is READ_WRITE variable, onFanChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFanChange()  {
  if(fan)
    digitalWrite(RELAY3,LOW);
  else
    digitalWrite(RELAY3,HIGH);
}
